### ISSUE TITLE
icons in buttons off-centre in "compact layout"

### ISSUE THREAD

**Issue by braver** [atom/one-dark-ui#103]
![screen shot 2015-11-04 at 10 26 43](https://cloud.githubusercontent.com/assets/2543659/10934438/370446de-82e0-11e5-9304-d0b386321590.png)
![screen shot 2015-11-04 at 10 26 47](https://cloud.githubusercontent.com/assets/2543659/10934440/37b9c77a-82e0-11e5-900d-425d0838ed49.png)

In none of the buttons-with-icons the icons sit comfortably in the centre.

**Comment by ssorallen** [comment]
I believe this is an issue in core. I opened a task for small buttons in the core stylesheet: https://github.com/atom/atom/issues/8412
