### ISSUE TITLE
Sidepanel

### ISSUE THREAD

**Issue by amarie004** [atom/one-dark-ui#105]
The side panel is highlighting all the modules on the side ... which leads me to believe they are all selected and/or open? I only have one tab open. This is causing ATOM to run extremely SLOW.

**Comment by lee-dohm** [comment]
What do you mean by the "sidepanel"? Do you mean the tree view?

<img width="520" alt="napkin 11-06-15 2 32 18 pm" src="https://cloud.githubusercontent.com/assets/1038121/11010379/2febcae8-8493-11e5-9607-a9922ffc0008.png">

Can you include a screenshot or GIF of what you're talking about?

**Comment by amarie004** [comment]
Yes! I meant tree view. Screenshot included:

**Comment by 50Wliu** [comment]
Hey @amarie004, Github doesn't show pictures that are attached to emails.  Can you please navigate to the issue on Github and then re-attach your screenshot?  Thanks!

**Comment by amarie004** [comment]
Sorry about that... here it is.
<img width="347" alt="screenshot" src="https://cloud.githubusercontent.com/assets/8523645/11010647/514da9ca-84ae-11e5-8343-997377667abd.png">

**Comment by lee-dohm** [comment]
No, it doesn't mean that they are selected or open ... only that they are new as far as the Git repository is concerned. Even with *lots* of new files, this should be very quick and shouldn't be the cause of any performance problem. In any case, it isn't an issue with the theme in any way.

Have you followed the suggestions in the [Debugging document](https://atom.io/docs/latest/hacking-atom-debugging)? Also, could you give the following information?

* Which version of Atom are you using?
* What OS and version are you running?
* Do you have [Emmet](https://atom.io/packages/emmet) installed?
* Can you reproduce the **performance** issue after completely exiting Atom and restarting using `atom --safe`?

**Comment by amarie004** [comment]
I'll go over the docs and get you the requested info by Monday. The performance has rapidly slowed. Thank you.

**Comment by amarie004** [comment]
Which version of Atom are you using?
1.1.0
What OS and version are you running?
OS X El Capitan, Version: 10.11.1
Do you have Emmet <https://atom.io/packages/emmet> installed?
Just install Emmet right now. 
Can you reproduce the performance issue after completely exiting Atom and restarting using atom --safe?
No… looks like it might be one of the packages. 
Current packages being used: 
atom-smart-tabs	emmet		minimap		trailing-spaces
atom-jinja2	color-picker	language-swig	script

**Comment by 50Wliu** [comment]
> Can you reproduce the performance issue after completely exiting Atom and restarting using atom --safe?
> No... works well.

Ok, that means one of your packages is causing this issue.  Try disabling them one by one until your issue is fixed.

**Comment by amarie004** [comment]
@50Wliu @lee-dohm I spoke to soon... it's still running slow on --safe mode
