### ISSUE TITLE
Tab looks wrong

### ISSUE THREAD

**Issue by havthgem** [atom/one-dark-ui#106]
<img width="355" alt="screen shot 2015-11-06 at 17 33 20" src="https://cloud.githubusercontent.com/assets/11625453/10993779/88d18670-84ac-11e5-99fa-f6d7cf281839.png">

Tab's content area bottom is cover editor's border top line.

I tried to change this content area height to 36 (origin: 37), looks good.

**Comment by simurai** [comment]
@havthgem Thanks for reporting.
