### ISSUE TITLE
Tree View is broken

### ISSUE THREAD

**Issue by havthgem** [atom/one-dark-ui#111]
<img width="191" alt="screen shot 2015-11-25 at 14 39 48" src="https://cloud.githubusercontent.com/assets/11625453/11390374/745efc5e-9384-11e5-991b-5c94718176f0.png">

**Comment by simurai** [comment]
What version of Atom are you using?

It looks like something is pushing down the tree-view. Did you install a package recently? If run `atom --safe` it should open Atom without any packages enabled.

**Comment by havthgem** [comment]
I check up, you are right.
Is a `terminal-list-view` on top, form `term3` package.

**Comment by mnquintana** [comment]
Thanks for the update @havthgem! Feel free to open an issue on [term3's repo](https://github.com/Floobits/atom-term3).

**Comment by simurai** [comment]
@havthgem You could move the margin to the header so it doesn't show initially.. in your `styles.less` add:

```less
terminal-list-view {
  margin-top: 0;
  .header {
    margin-top: 10px;
  }
}
```

I'll make a PR for that too.

**Comment by havthgem** [comment]
@simurai Thank you.
