### ISSUE TITLE
one-dark-ui theme can't update.

### ISSUE THREAD

**Issue by havthgem** [atom/one-dark-ui#115]
one-dark-ui newer release version is 1.1.9, but my version is 1.1.5.
My Atom version is 1.3.2.

**Comment by 50Wliu** [comment]
One Dark UI is a bundled theme that will only update when Atom is updated.  Atom 1.3.2 comes with one-dark-ui 1.1.5, so it will not update further.

**Comment by havthgem** [comment]
I'm clear, thank you.
