### ISSUE TITLE
Highlight in tree view should not scroll

### ISSUE THREAD

**Issue by Aluxian** [atom/one-dark-ui#122]
Change [this line](https://github.com/atom/one-dark-ui/blob/6207ec3ad20d164989ec332da14802b7ac169ec0/styles/tree-view.less#L66) to

```
position: absolute;
```

**Before:**

<img width="151" alt="screen shot 2016-02-10 at 12 35 50" src="https://cloud.githubusercontent.com/assets/1418870/12944908/e44798fa-cff2-11e5-8cba-93db6f9905ad.png">

When I scroll down, the highlighted line scrolls down with the content.

**After:**

<img width="99" alt="screen shot 2016-02-10 at 12 36 06" src="https://cloud.githubusercontent.com/assets/1418870/12944910/e87800d6-cff2-11e5-9aff-251eeab89fab.png">

The line stays there.

Hope it helps.

**Comment by lee-dohm** [comment]
Are you suggesting the same thing as in this PR? https://github.com/atom/one-dark-ui/pull/119

**Comment by Aluxian** [comment]
Yes, it's the same thing. I should've searched more, sorry. Now I understand the decision and I'll close this. I modified my stylesheet and I'm happy with how the theme looks overall. Thanks!

**Comment by lee-dohm** [comment]
Thanks for the update. I'm glad things are working for you!
