### ISSUE TITLE
Tabs have uneven width

### ISSUE THREAD

**Issue by 2426021684** [atom/one-dark-ui#130]
In the lastest version the tabs have different widths. I have compact mode enabled.

**Comment by 50Wliu** [comment]
This was added in #124.

I must admit that I liked the old layout better - a config option for that would be fantastic, though of course that could also open up the path for tons of more config option requests.

**Comment by simurai** [comment]
Ya, we could make it a separate config. I was thinking to first test it out part of the "compact mode" since it's somewhat related.

**Comment by 2426021684** [comment]
@simurai working on pull request
