### ISSUE TITLE
bash syntax highlight theme one-dark: problem with comment string

### ISSUE THREAD

**Issue by Manu-sh** [atom/one-dark-ui#137]
my code is:  
  for i in $(cat $gnu_cache_dir/list.lst); do #scan subdirectory listed in gnu_filelist
     ....

in this string after "do" if i write "in" comment is not highlight correctly.
I can upload a screenshot on my server and paste link here if you don't understand

**Comment by simurai** [comment]
Screenshot would be great. Also, what kind of language package are you using to add syntax highlighting?

**Comment by Manu-sh** [comment]
I have try with different syntax theme and UI theme but i have got same issue, I do not know where I can report this issue maybe on atom master:

http://chilios.altervista.org/atom_issue_b.png
http://chilios.altervista.org/atom_issue_a.png

encoding is utf 8, language pack i don't know i think so en or us, i have default config except for the wrapper package (i have disable) syntax theme and ui theme, but theme is not problem.

**Comment by simurai** [comment]
I see. Yeah, I can reproduce this too. It thinks the `in` is part of the `for` loop and not the comment:

![comment](https://cloud.githubusercontent.com/assets/378023/15950344/d1a4da78-2ee8-11e6-8612-4786152a455d.gif)

Do you mind opening an issue in this package: https://github.com/atom/language-shellscript.

There is already an open PR https://github.com/atom/language-shellscript/pull/36, but not sure if that would fix this too.
