### ISSUE TITLE
Tabs expanding whole editor pane when overflowing

### ISSUE THREAD

**Issue by adambuczynski** [atom/one-dark-ui#138]
cc @simurai 

This is with Atom 1.10.0-dev-672cf6d

I suspect this has to do with the tabs. When there's too many open, at one point they stop shrinking, but instead expand the editor pane beyond the bounds of Atom's window:

![image](https://cloud.githubusercontent.com/assets/490562/15840511/54e98534-2c9e-11e6-84cd-90067c05aebd.png)

After closing some of the tabs, the editor pane becomes smaller and fits inside the Atom window again:

![image](https://cloud.githubusercontent.com/assets/490562/15840536/88a5f13c-2c9e-11e6-892c-3bf57e774e95.png)

Probably need to apply a `max-width` on one of the parent containers.

**Comment by simurai** [comment]
@adambuczynski Thanks for catching this. :ok_hand: Ya, looks like it's the same as those other overflowing issues. Should be fixed with https://github.com/atom/atom/issues/11930

**Comment by adambuczynski** [comment]
Great, thank you
