### ISSUE TITLE
Tabs have uneven width (Atom 1.8.0)

### ISSUE THREAD

**Issue by sadikovi** [atom/one-dark-ui#139]
Just updated to Atom 1.8.0 and tabs have uneven width again, similar to #130. It is not a big deal, but I loved when all tabs were sized similarly, which worked in 1.7.x before update.

Here is a screenshot:
<img width="892" alt="sample" src="https://cloud.githubusercontent.com/assets/7788766/15852582/a542807e-2cf5-11e6-98e9-a629de329510.png">

**Comment by sadikovi** [comment]
Guys, is it by design or a bug? Or, if there a configuration option somewhere to disable this, I would appreciate someone pointing out to it.

**Comment by 50Wliu** [comment]
@sadikovi In the One Dark UI settings, change "Tab Sizing" to "Even".

**Comment by simurai** [comment]
Just in case somebody can't find the theme settings:

![screen shot 2016-06-08 at 11 27 52 pm](https://cloud.githubusercontent.com/assets/378023/15897902/2d9a9fe8-2dd1-11e6-93fb-9b59f46bc2c8.png)
![screen shot 2016-06-08 at 11 29 06 pm](https://cloud.githubusercontent.com/assets/378023/15897903/2d9b42ae-2dd1-11e6-9dc3-d99cb3a895e6.png)

**Comment by lee-dohm** [comment]
Used the images here for the [Atom FAQ entry I wrote](). Thanks @simurai!

**Comment by sadikovi** [comment]
Thanks @50Wliu @simurai.
@lee-dohm Can you update link for FAQ? it redirects to this issue.

**Comment by simurai** [comment]
@sadikovi I think it's this: https://discuss.atom.io/t/the-tabs-got-shorter-in-v1-8-0-what-happened-how-do-i-go-back/29791
