### ISSUE TITLE
Tree view ignored color has very lower contrast in Atom Dark Syntax

### ISSUE THREAD

**Issue by kevinsawicki** [atom/one-dark-ui#14]
![screen shot 2015-02-12 at 3 11 56 pm](https://cloud.githubusercontent.com/assets/671378/6179050/d933159e-b2c9-11e4-9b41-2b26b766b660.png)

**Comment by simurai** [comment]
Before and after:

![screen shot 2015-02-13 at 3 10 54 pm](https://cloud.githubusercontent.com/assets/378023/6183022/9d5de886-b392-11e4-847f-7a8fd2323f13.png)
