### ISSUE TITLE
Template string highlighting issue

### ISSUE THREAD

**Issue by xscheiner** [atom/one-dark-ui#146]
I have a method call that uses a long template in one arg string so that I have to split the args of the call onto separate lines. Notice what happens to the template string highlighting when I do that:

![image](https://cloud.githubusercontent.com/assets/1236507/16307165/2e3f9128-3958-11e6-936e-c0bfbeff65c0.png)

You can see the back-ticks are green, but the text should also be green as it is in other template strings.

**Comment by 50Wliu** [comment]
Please report this on the appropriate language package, eg `atom/language-javascript` for JavaScript.
