### ISSUE TITLE
Editor not overflowing properly

### ISSUE THREAD

**Issue by mmcbride1007** [atom/one-dark-ui#148]
Lately I've noticed some issues with the overflow of the editor. Tabs won't scroll, the find and replace panel goes off the side of the screen. It almost looks like the editor isn't aware of the width of the project files panel. See the screencap of the find and replace panel as I adjust the files panel and notice how the buttons get pushed way off the side of the screen. The same thing happens with tabs:

![one-dark-ui-overflow](https://cloud.githubusercontent.com/assets/6248612/16342516/3810903a-39f8-11e6-9261-473a4d3f2bc2.gif)

I haven't had time to dig into this yet but I'll try and find the properties that are causing this, but wanted to get this out there.

I'm running 1.9.0-beta0

**Comment by 50Wliu** [comment]
This has been fixed and will be out in the next 1.9.0 beta.

**Comment by mmcbride1007** [comment]
Thanks!
