### ISSUE TITLE
Hard to tell what the current-result is

### ISSUE THREAD

**Issue by braver** [atom/one-dark-ui#15]
The way search results in an editor are highlighted, it's hard to tell the current-result from all the other results. This is important because if you exit the search, that's where your cursor is at. Also, walking through the results with find-next is easier if you know where to look. 
I think this is mostly a concern of the syntax theme, but I don't think many syntax themes pay attention to this and the UI theme should provide a good default. Haven't figured out how to handle that myself yet, but I figured I'd at least report it here and share this thought.

![screen shot 2015-02-17 at 23 17 53](https://cloud.githubusercontent.com/assets/2543659/6238511/f9668c52-b6fb-11e4-987b-3bfdd05eb1ad.png)

Edit: Sublime uses a yellow background, Safari (OS X in general) also uses a yellow highlight.

**Comment by braver** [comment]
Nevermind, I see that in one-dark-syntax it's actually pretty good. Not in your face, but visible. Just that a lot of other syntax themes overlook this (perhaps because they were converted from Sublime/Textmate that offer a pretty good default).

**Comment by simurai** [comment]
Doesn't `current-result` only get added after you hit "find next"? If I `esc` without it, my cursor is at the same place before I started a search.

And when doing a "find next", in One's case, it's an orange border color.

![screen shot 2015-02-18 at 8 58 28 pm](https://cloud.githubusercontent.com/assets/378023/6247085/999c1766-b7b3-11e4-8079-2fa4e3a5ea60.png)

Maybe not all themes define a strong enough `@syntax-result-marker-color-selected`: https://github.com/atom/find-and-replace/blob/master/styles/find-and-replace.less#L21

**Comment by simurai** [comment]
Ohh.. didn't see your 2nd comment. Had this issue as a tab open.
