### ISSUE TITLE
Tabs not resizing

### ISSUE THREAD

**Issue by cortopy** [atom/one-dark-ui#154]
According to the settings `Tab Sizing>Auto` will resize tabs based on window size. However, if I put Atom to half size of my screen on the right, tabs overflow outside the screen and I have to maximise to see them. The same happens with "minimum".

The only way to have tabs resizing is to have `Tab Sizing` on Even.

**Comment by simurai** [comment]
Sorry, the description might not be clear enough. `Tab Sizing > Auto` means that it automatically switches between the `Minimum` and the `Even` mode depending how wide the window is. Not that the tabs itself are based on the window width.

So you can pick either `Minimum` or `Even` or let it automaically switch between them with `Auto`.

Hope that helps.

**Comment by cortopy** [comment]
My issue was to do with overflow rather than functionality. Basically, in either Auto or Minimum, tabs overflow the screen and I can neither see or click on them

**Comment by mmcbride1007** [comment]
@cortopy what version of Atom are you running? This was a bug I also encountered in 1.9 beta and was fixed in 1.10 beta. Wondering if it's still there in 1.9 stable? cc: @thomasjo do you know?

**Comment by cortopy** [comment]
I noticed this with 1.9.0 stable, I just upgraded to 1.9.6 and I can see same behaviour

**Comment by simurai** [comment]
Ok, I think you mean that the active tab is not "scrolled into view" and you have to manually do it:

![scroll-tabs](https://cloud.githubusercontent.com/assets/378023/18080350/29cb9fbc-6ed0-11e6-81b4-8805cd6c83ce.gif)

I agree, that's a bit annoying. There is an issue open about it: https://github.com/atom/tabs/issues/138

**Comment by v3ss0n** [comment]
yeah we have that issue for so long. Nobody know how to fix that yet , even lead maintainer of tabs i think. He is missing in action for so long.
