### ISSUE TITLE
Changes to install/selected button colors

### ISSUE THREAD

**Issue by Zirro** [atom/one-dark-ui#156]
![Install button](https://s3.amazonaws.com/f.cl.ly/items/3h0i3Z3S0U1r3Z2t2110/install_button.png)

The left button is from Stable and the right from Beta. I'm filing this issue under the assumption that the change was unintentional since I don't think the black text is an improvement. It has less contrast and looks blurry together with the text shadow.

EDIT: I've realized that this color derives from the syntax theme. I am using Base16 Tomorrow Dark. Does the issue still belong here or should I create one in that repo?

**Comment by simurai** [comment]
> I've realized that this color derives from the syntax theme.

Yeah, right. The accent color is based on the background of the syntax theme. We can play a bit more with the foreground/background contrast.

**Comment by karl** [comment]
I've also noticed that the colours and contrast on the action buttons and checkboxes got much worse in this update.

They went from a nice green to a disturbingly bright blue, with the same black text with shadows issue mentioned above.

![image](https://cloud.githubusercontent.com/assets/3681/18172509/a06e0356-705d-11e6-9143-6ba7a3fac395.png)

Is there any way to control what background and foreground colour are used here? I'd like to go for something less eye melting 😛

**Comment by simurai** [comment]
There is now a PR that addresses this issue: https://github.com/atom/one-dark-ui/pull/171.

Here with a few themes:

One Dark | Base16 Tomorrow Dark | Solarized Dark
--- | --- | ---
![screen shot 2016-10-12 at 11 12 13 am](https://cloud.githubusercontent.com/assets/378023/19295048/d2b05538-906c-11e6-9bc3-eb70aece3d38.png) | ![screen shot 2016-10-12 at 11 11 55 am](https://cloud.githubusercontent.com/assets/378023/19295049/d2b249ce-906c-11e6-8723-7d7644970160.png) | ![screen shot 2016-10-12 at 11 11 34 am](https://cloud.githubusercontent.com/assets/378023/19295050/d2b38d20-906c-11e6-9b27-79681749c522.png)


Solarized Dark is still pretty light (and has an inverted text color). Maybe there can be some sort of upper limit.

**Comment by simurai** [comment]
The changes in #171 will be part of Atom `1.13`. It's not exactly how it used to be, it depends on the syntax theme used.

Feel free to add a comment if somebody wants to customize it further.

**Comment by 9585999** [comment]
Hello, how I can change to previous version color???

**Comment by simurai** [comment]
@9585999 Unfortunately that's not possible in an easy way.

- You _could_ override buttons etc. in your `styles.less` file, but there would be quite a few places.
- Or install a previous version, but then there wouldn't be any updates.
- Or maintain your own forked theme.
