### ISSUE TITLE
file modified indicator overlaps filename

### ISSUE THREAD

**Issue by braver** [atom/one-dark-ui#157]
![screen shot 2016-08-09 at 10 15 22](https://cloud.githubusercontent.com/assets/2543659/17509471/4f0900ba-5e1a-11e6-8cf7-909d3690c324.png)

X-icons are only shown on hover, with a subtle shadow behind them to prevent overlap with filenames. However, the modified indication dot is always visible but lacks the shadow.

**Comment by 50Wliu** [comment]
This has already been fixed in #144.
