### ISSUE TITLE
Tab sizing is not enough when in auto mode

### ISSUE THREAD

**Issue by StephenHesperus** [atom/one-dark-ui#158]
![capture](https://cloud.githubusercontent.com/assets/4600585/17724280/5f067dc6-6473-11e6-85c1-0a32af13133f.PNG)

Please take a look at the tabs, the blue dot is overlapping with the text "untitled".

**Comment by mmcbride1007** [comment]
I think this is a duplicate of #153

**Comment by StephenHesperus** [comment]
I see, thank you. Then I'll wait for v1.10 :smile:
