### ISSUE TITLE
Tabs drop marker went missing

### ISSUE THREAD

**Issue by simurai** [atom/one-dark-ui#169]
> @Ben3eeE The blue bar indicating where to drop is always to the left on `1.12.0-dev-24c8343`.

![blue_tab_dropping_indicator_480](https://cloud.githubusercontent.com/assets/378023/19205354/e06f18e2-8d1c-11e6-9b10-f68b23fdf6dc.gif)

**Comment by 50Wliu** [comment]
Oh true, I was wondering where that went!

**Comment by simurai** [comment]
Actually, this seems to affect all themes.

Moved to https://github.com/atom/tabs/issues/383
