### ISSUE TITLE
Close tab button for Macs

### ISSUE THREAD

**Issue by partydrone** [atom/one-dark-ui#179]
It would be nice to maintain consistency by having the close tab button on the left side of tabs for Macs. Some ideas include:
- a configuration option
- a separate theme
- automatically detected based on the OS

**Comment by simurai** [comment]
This came up already in https://github.com/atom/one-dark-ui/pull/95 and was closed as `wontfix` (for now).

I think if this theme should support it, then only as a configuration option to not mess with people's muscle memory.

There are also these additional options:

- See if there is a package for it? Maybe [this](https://atom.io/packages/close-on-left), [this](https://atom.io/packages/close-button-on-left) or [this](https://atom.io/packages/tabs-close-icon-left).
- Point people to https://github.com/atom/one-dark-ui/pull/95#issuecomment-199668345 so they can override it in their `styles.less` file.

**Comment by Ben3eeE** [comment]
@simurai see also https://github.com/atom/tabs/issues/378

**Comment by simurai** [comment]
yeah, doing it the tabs package would be ideal, but probably hard to not break existing packages/themes. For example the One themes have some custom gradient mask for the text that would need to be switched direction.

**Comment by simurai** [comment]
Closing, this is now supported in the theme settings:

![image](https://user-images.githubusercontent.com/378023/44467078-ed1b6e00-a65c-11e8-8663-a15fca5a25eb.png)
