### ISSUE TITLE
MarkdownPreviewView tabs are not seamless

### ISSUE THREAD

**Issue by braver** [atom/one-dark-ui#18]
This is another data-type you can style! Also, git-control has a different background (I think it takes the tool-panel background), so you could consider styling that with GitControlView.

... I'm not sure how to manage this exactly, hope the variations don't get out of hand ;)

https://github.com/braver/isotope-ui/commit/8712cecbc7dcf6786def2711b60a7cf502d1d70e

**Comment by simurai** [comment]
@braver Good point. :+1: 

For `git-control` I ended overriding its background instead. It uses `@app-background-color` which I think isn't really meant to be used in a pane. I find in general hard to pick variables since not everyone understands them the same. Maybe there needs to be a "guide" or so. When to use what variable.

**Comment by simurai** [comment]
And yep.. creating a theme is kinda never ending if you also dive into styling packages.

For markdown-preview I wonder if a theme should override the default styles so it fits UI colors. Maybe with a checkbox to turn it off again.

**Comment by braver** [comment]
Yeah, I wonder how far you should go down that path. A lot of developers don't have the design skills and end up with ugly stuff. My current thinking is that it's better to work with them, send in some PR's to help with styling. I'm also contemplating creating a list of tweaks you can put in your personal stylesheet. All of that is easier to maintain that incorporating tweaks into the theme.

There would definitely be value in making more of a gui guide though. When to use what variable, some do's and don'ts. The Styleguide is a good start, but some general guidance on stuff like the app-background that git-control was using, would definitely help getting the packages to a higher level.

**Comment by simurai** [comment]
Maybe the line could be drawn between core and community packages. It's ok to style anything in core, but for community packages it's better to make a PR or just do it personally in `styles.less`.
