### ISSUE TITLE
Question: Possibility to change the highlight color?

### ISSUE THREAD

**Issue by mischah** [atom/one-dark-ui#180]
First of all: I love this UI-Theme ❤️ 

But I would love to change the highlight color (currently a blue) to something more subtle.

![highlight](https://cloud.githubusercontent.com/assets/441011/19840368/47f97f78-9ef4-11e6-8ba3-e2192500b5c6.png)

Is that possible? 

Would be great to be able to change that in the settings.

**Comment by simurai** [comment]
> Would be great to be able to change that in the settings.

There was an attempt a while ago https://github.com/atom/one-dark-ui/pull/141 but was closed later. We would still have to figure out a way to make the text readable. See the 4 options in that PR.

If you're familiar with CSS, you could always override it in your `styles.less` file, like

```
.tooltip .tooltip-inner {
  color: black;
  background-color: white;
}
.tooltip.top .tooltip-arrow    { border-top-color:    white; }
.tooltip.left .tooltip-arrow   { border-left-color:   white; }
.tooltip.right .tooltip-arrow  { border-right-color:  white; }
.tooltip.bottom .tooltip-arrow { border-bottom-color: white; }
```

but that's a lot of overriding for all the places the accent color is used.

**Comment by davidbarredo** [comment]
I would love this feature.

Maybe two color selectors, one for the accent color and another for the text is a simple way to solve it.

**Comment by davidbarredo** [comment]
Is there any hope to recover the changes in #141?

Maybe the third option in that PR is the safest.

**Comment by simurai** [comment]
Closing this as stale.
