### ISSUE TITLE
Poor performance with theme set

### ISSUE THREAD

**Issue by hugoamvieira** [atom/one-dark-ui#182]
I've noticed that when I have the One Dark UI set, Atom behaves much more slowly on opening projects, files and navigating around.

**Comment by simurai** [comment]
There are probably differences but it shouldn't be too noticeable.

If you don't mind posting a gif for this theme and another (where it's less slow), that would be great to compare. Also, is it still slow when running Atom in [Safe Mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?

**Comment by hugoamvieira** [comment]
Sure, @simurai I'll try to make a comparison gif and I'll link it here

**Comment by hugoamvieira** [comment]
Weird, I cannot reproduce this anymore. 
Anyways, I'll close this and if it happens again I'll be sure to do a repro ASAP :)

Thanks!

**Comment by simurai** [comment]
It might be [this](https://github.com/atom/one-dark-ui/commit/0e84472c27d28535af5d421c101c8d24086e0942) that fixed it. After adding it, scrolling seemed smoother.

**Comment by hugoamvieira** [comment]
Yeah, I've tried a few more times to reproduce and I still wasn't able to.
