### ISSUE TITLE
Active pane marker disappeared when the window is close by cmd+w

### ISSUE THREAD

**Issue by ooJerryLeeoo** [atom/one-dark-ui#204]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

As the title.

### Steps to Reproduce

1. Project window
2. Open few tabs
3. Close the window by keep press <kbd>cmd</kbd>+<kbd>w</kbd>  // not  <kbd>cmd</kbd>+<kbd>shift</kbd>+<kbd>w</kbd>
4. Reopen the window, and you'll see the :bug:

**Expected behavior:** The active pane marker should be shown.

**Actual behavior:** The active pane marker is disappeared.

### Versions

`Atom`: `Atom1.17.0-beta2`  
`OS`: `macOS sierra`

**Comment by simurai** [comment]
Yes, noticed that too. Still have to look into it, but I think that `atom-pane`s don't receive the `.active` class anymore.

**Comment by simurai** [comment]
This is currently blocked by https://github.com/atom/atom/issues/14283.

**Comment by simurai** [comment]
The tree-view pane marker got fixed with https://github.com/atom/one-dark-ui/commit/1f2830f962908414705c902902ec27b0811af4b2.

But the tabs still require a split pane to work.

**Comment by simurai** [comment]
We might can unblock this earlier by adding `blinkFeatures:` [CSSSelectorsFocusWithin](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/platform/RuntimeEnabledFeatures.json5?l=294) to [webPreferences](https://github.com/atom/atom/blob/84d07e351c2c21c8a37f9d0fded04aae5eabc750/src/main-process/atom-window.coffee#L29)

```coffee
blinkFeatures: 'CSSSelectorsFocusWithin'
```

Then the `:focus-within` selector should work.

**Comment by simurai** [comment]
This got fixed with #248
