### ISSUE TITLE
Utilize @font-size variable

### ISSUE THREAD

**Issue by Arcanemagus** [atom/one-dark-ui#205]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

This theme is [_directly_ modifying](https://github.com/atom/one-dark-ui/blob/1704a0c019eda7adad376a553bfdd14994a8674e/lib/main.coffee#L29) the font size through the DOM API, not the LESS variable defined in Atom for this purpose.

### Steps to Reproduce

1. Attempt to utilize `@font-size` effectively in a package
2. ...?
3. No profit 😞

**Expected behavior:**

This theme uses the `@font-size` variable outlined in Atom's [ui-variables.less](https://github.com/atom/atom/blob/636df2c84ce828042527986aad2266aa8dd30642/static/variables/ui-variables.less#L69).

**Actual behavior:**

`@font-size` is unused here, meaning changing the font size in the settings doesn't affect things attempting to use that variable to render content that matches the theme.

**Reproduces how often:**

100% of the time.

### Versions

Atom v1.17.0-beta3
`one-dark-ui@1.10.3`

### Additional Information

Originally filed as https://github.com/steelbrain/linter-ui-default/issues/262.

**Comment by simurai** [comment]
> `@font-size` is unused here

This theme sets the `@font-size` to `12px` [here](https://github.com/atom/one-dark-ui/blob/master/styles/ui-variables.less#L83). 

The problem is that if a package uses `@font-size` it will always stay at `12px` and unfortunately not get updated when a user changes the Font Size in the theme settings. Changing it there only has support for some bundled packages, but not all community packages. So users have to do it themselves in their `style.less` file.

There is an old idea https://github.com/atom/atom/issues/5903 for adding a `user-variables.less` file, where `@font-size` could be changed and then this theme wouldn't need the settings option.

**Comment by Arcanemagus** [comment]
Bizarre, [this code](https://github.com/atom-material/atom-material-ui/blob/81b7bfdc08c92b3c43923651fabea50702cd6bb8/lib/settings.js#L44-L47) seems to be working on _one_ computer I use, but not the other. The only difference is the working one is v1.17.0-beta3 and the one that doesn't update is v1.17.0-beta0.

Unfortunately I'm not a UI guy, so I don't know how to debug this further, but would be happy to help in any way I can!

**Comment by simurai** [comment]
How does it look if you paste this in `styles.less`:

```less
.sb-table.linter {
  font-size: 1em;
}
```

Then it should pick up the Font Size from the theme settings.

**Comment by Arcanemagus** [comment]
It looks like that style change makes it update with the way that `one-dark-ui` updates the font size, and still work with the way that `atom-material-ui` is updating it on my work computer where the `atom-material-ui` method works.

I'll have to check again tonight as to why both current methods fail on the laptop.

**Comment by simurai** [comment]
Another idea: Use `zoom`. Then it can be `px` everywhere and you can still zoom in/out like with `em` units:

![zoom](https://cloud.githubusercontent.com/assets/378023/25947086/ef817f58-3688-11e7-9587-fbe39c231a29.gif)

Sometimes there are issues with "snapping to whole pixels", but maybe ok given the accessibility improvements.

**Comment by Arcanemagus** [comment]
That actually sounds like a _very_ nice solution to what people are likely desiring with increasing the font size.

**Comment by lloiser** [comment]
This problem will probably affect more people now: the new github plugin ignores the font-size setting of one-dark-ui 😢 

![screen shot 2017-06-16 at 10 47 46](https://user-images.githubusercontent.com/3003233/27219268-614eabba-5281-11e7-8712-8e71777d7332.png)

As @Arcanemagus already mentioned: one-dark-ui just modifies the font-size on the root node but the github plugin uses the `@font-size` variable ...
https://github.com/atom/github/blob/v0.3.3/styles/git-panel.less

**Comment by simurai** [comment]
Right. one-dark-ui still needs to add support for making the GitHub package change based on the  settings.

**Comment by simurai** [comment]
Gonna close this as stale.

- Package authors can still use `@font-size`. It won't be affected by this theme's settings.
- Package authors can use `em` units, like `font-size: 1.2em;`. Then the font size scales depending on the parent elements. But it's a bit unpredictable.
