### ISSUE TITLE
Cutom-inset title bar

### ISSUE THREAD

**Issue by kajka** [atom/one-dark-ui#207]
Hi there!

First of all: I would like to thank you for the tremendous work in creating this fantastic theme!

Secondly: Atom now has an "experimental" function for the title bar. I liked the idea of [Neutron Dark UI](https://atom.io/themes/neutron-dark-ui) very much. The question is: can I achieve the same result with One Dark UI? Do you need to implement this solution?

![screen shot 2017-05-15 at 18 23 33](https://cloud.githubusercontent.com/assets/2843796/26068092/9bd35586-399c-11e7-8a07-99dd9c4a2814.png)

Cheers!

**Comment by simurai** [comment]
There are a few edge cases where things could look broken, see https://github.com/atom/atom/pull/10208#issuecomment-248550174. Probably most people will not see them, but it's still a bit risky for a default theme.

Maybe it's better to leave it to other themes, or your `styles.less`. There is also packages like https://atom.io/packages/no-title-bar that should work.
