### ISSUE TITLE
Tab active indicator has vision issue

### ISSUE THREAD

**Issue by havthgem** [atom/one-dark-ui#208]
<img width="51" alt="screen shot 2017-05-17 at 17 59 01" src="https://cloud.githubusercontent.com/assets/11625453/26148833/91a800ae-3b2a-11e7-8677-69c495f7d3ed.png">
Active indicator has 1px blank on the left.

Why do not `border-left: 0px solid @base-border-color` replace `border-left-color: transparent`.

**Comment by simurai** [comment]
Fixed in https://github.com/atom/one-dark-ui/commit/1f2830f962908414705c902902ec27b0811af4b2

![image](https://cloud.githubusercontent.com/assets/378023/26612520/42cf9ec6-45f0-11e7-8beb-ca63bbf091d5.png)
