### ISSUE TITLE
Settings/Readme disparity

### ISSUE THREAD

**Issue by jsejcksn** [atom/one-dark-ui#210]
> Reporting from Atom `1.17.0` and One Dark `1.10.3`

The Readme mentions options I don't see in my settings: a _Layout Modes_ section and _Tab Sizing_ modes: `Auto` `Minimum`, and `Even`. Screenshot from the Readme:

![Readme settings screenshot](https://cloud.githubusercontent.com/assets/378023/15923548/cb3dc7ce-2e68-11e6-8a51-10801fb483bf.png)

I have very different settings than what is pictured/described. Here's a screenshot from my installation:

<img src="https://cloud.githubusercontent.com/assets/868251/26213684/92ad663e-3bbf-11e7-820e-a410a1562bd1.gif" alt="one-dark-ui-settings" width="494">

Is this a change in the 1.10.4 release?

**Comment by zhangbenber** [comment]
I find the option `Layout Mode` disappeared too. All the UI elements seem to be set to `Compact` layout mode after upgrading, even if the window is large enough.
I have Atom 1.17.0 and One Dark 1.10.3, the same as @jsejcksn.

**Comment by mmcbride1007** [comment]
Yes, this is recently removed, you can see more details about why that option was removed in #198 which shipped with `1.17`

**Comment by simurai** [comment]
☝️  @mmcbride1007 is correct. The [README](https://github.com/atom/one-dark-ui/blob/master/README.md) is now updated too.
