### ISSUE TITLE
UI font size cannot be set

### ISSUE THREAD

**Issue by KSSea** [atom/one-dark-ui#213]
I try to change the UI font size to any setting other than auto.  If for example I type "13" in the box the UI automatically rescales and the value changes to 20.  This happens for any value > 12 which is typed in the box: it always changes to 20.

**Comment by simurai** [comment]
I think it's the same problem as described here: https://github.com/atom/one-light-ui/issues/47#issuecomment-162120573. You have to type `13` quick enough before the change gets applied. I think it's like 1 second.
