### ISSUE TITLE
When tool-bar is on the left, there is blue vertical line on top of it

### ISSUE THREAD

**Issue by yuriihabrusiev** [atom/one-dark-ui#214]
<img width="121" alt="screen shot 2017-06-29 at 2 22 01 am" src="https://user-images.githubusercontent.com/901000/27664928-d8041c04-5c72-11e7-9f06-ce664169b1c1.png">

Same with `one-light-ui`

**Comment by simurai** [comment]
This should already be fixed in Atom `1.19`, currently still `Beta`.
