### ISSUE TITLE
tree-view arrow icon for project root header not aligned properly

### ISSUE THREAD

**Issue by raphael-cch** [atom/one-dark-ui#222]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When the UI font size is not 12px, the arrow icon of the project root header does not align properly to the text, see screenshots in the tree view:

UI Font Size 18px | UI Font Size 8px
----------------- | -----------------
![image](https://user-images.githubusercontent.com/26691193/31309054-f117f3ba-ab77-11e7-9917-d80558d8c6fb.png) | ![image](https://user-images.githubusercontent.com/26691193/31309087-7b4e259a-ab78-11e7-8fbd-2c0d5a79d11d.png)

The arrow aligns properly for folders, but misaligns for the project root header.

### Steps to Reproduce

1. Go to the One Dark UI Settings page and change the Font Size to something other than 12
2. Open tree view

**Expected behavior:** Arrow should be horizontally centred with respect to the text, see screenshot for the 12px case:
![image](https://user-images.githubusercontent.com/26691193/31309109-e5d7eb62-ab78-11e7-89bd-b5d6fffaf822.png)

**Actual behavior:** Arrow is misaligned, see screenshots above.

**Reproduces how often:** 100%

### Versions
Atom 1.21.0, macOS 10.11.6

### Additional Information
After some digging around, I suspect this has to do with PR #217. The `line-height` of the arrow is 2.5em of the arrow font size (ie 12px), but the `line-height` of the project root header text is 2.5em of the selected UI font size. For me this issued could be fixed by using 2.5[rem](https://www.w3schools.com/cssref/css_units.asp) instead of 2.5em in [`.tree-view .project-root-header.project-root-header.project-root-header.project-root-header::before`](https://github.com/atom/one-dark-ui/blob/master/styles/tree-view.less), so the `line-height` of the arrow becomes 2.5em of the root element (ie UI font size selected by user), but I'm not sure this would work for all systems.

**Comment by simurai** [comment]
> @raphael-cch For me this issued could be fixed by using 2.5rem instead of 2.5em

Thanks for taking a look. 🙇  Yeah, that might work. Although a benefit of keep using `em`s is that then people can resize the tree-view individually and not just the global (root) font-size.

A solution in #228 is to make the arrow icons inherit the same font-size as the text label, then they scale together and should stay centered:

![icon](https://user-images.githubusercontent.com/378023/33591384-aae13cec-d9c8-11e7-8043-0c6bbf125092.gif)
