### ISSUE TITLE
Hard to see active tab when Tabs -> "Enable VCS Coloring" is enabled

### ISSUE THREAD

**Issue by ProLoser** [atom/one-dark-ui#226]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Originally I thought VCS coloring was overriding the active tab highlight (of pure white text) but I realized there's a very subtle tab background color when the tab is active which is nearly impossible to see if your brightness isn't set to absolute maximum or viewing conditions aren't perfectly optimal.

### Steps to Reproduce

1. Tabs -> Enable VCS Coloring
2. Open several VCS-modified files at once
3. Select one of the VCS-modified tabs

**Expected behavior:** [What you expect to happen]
This is what happens with the setting disabled. 
![image](https://user-images.githubusercontent.com/67395/33287175-af6d9fce-d36c-11e7-9fa2-7505a12aed1a.png)

**Actual behavior:** [What actually happens]

This is nearly impossible to discern without optimal screen viewing conditions
![image](https://user-images.githubusercontent.com/67395/33287187-c102626a-d36c-11e7-9b4e-65cbfdfc42ed.png)

### Versions

Atom: 1.22.1
Electron: 1.6.15
Chrome: 56.0.2924.87
Node: 7.4.0
OS: OSX 10.12.3

### Additional Information

I wasn't sure if this should be addressed within this package or within the tabs package, but since the instructions say to test if this persists in safe mode and it is not an obvious issue in safe mode I figured the responsibility falls on this package (which is a stylistic package) to play nicely with core behavior.

I don't off the top of my head have concrete ideas on how to address this as I sort of feel that VCS coloring _should_ persist on the currently active tab, but I feel there could be an improvement about this UI such as making the text bold, adding clearer separation of tabs, muting the sibling tab text, or something.

**Comment by ProLoser** [comment]
I've realized after switching to `one-light-ui` that the active tab coloration matches the Syntax Theme background which I currently have set to `Monokai` so perhaps this is just my IDE's configuration. I would still like to see something other than pure coloration differentiation.

**Comment by 50Wliu** [comment]
Hmm, the blue indicator on the left is missing.  I've been noticing that it only shows up sporadically now as well. @simurai

**Comment by ProLoser** [comment]
A few additional notes that lead to this problem:

1. Monokai's background color is extremely close to one-dark-ui
2. The 'muted' coloration of inactive tabs is lost when VCS coloring is enabled
3. The 'active' coloration of active tabs (bright white text) is lost when VCS coloring is enabled
4. The blue line for the active tab is missing as @50Wliu pointed out

I'm not a huge fan of the blue line as I don't find it super intuitive. Placed between 2 tabs, it's not immediately clear which one it corresponds to (if you're new to this theme).

I think the issue can be better addressed by instead restoring muted colors and brighter colors to active and inactive tabs. The blue line seems out of place within this theme and I would propose putting it on both sides and top of an active tab if you really wanted to keep it.

**Comment by ProLoser** [comment]
Tried to add muted colors myself but got a bit confused about how to do this quickly within less so I gave up lol.

**Comment by simurai** [comment]
> @50Wliu Hmm, the blue indicator on the left of the active tab is missing. I've been noticing that it only shows up sporadically now as well.

The blue indicator only appears once you split into 2 panes. See https://github.com/atom/atom/issues/14283

@ProLoser I can see 2 options:

1. Dim/fade the VCS coloring for not active tabs.
2. Use some other way, like an extra dot. Similar to un-saved.

I'll try option 1 first, since it seems simpler.

**Comment by simurai** [comment]
@ProLoser How does 

![vcs](https://user-images.githubusercontent.com/378023/33694631-91390944-db3c-11e7-86ab-ddb979f51385.gif)

feel? PR -> #230
