### ISSUE TITLE
When changing font size by entering double digit integer value the UI font size resets 

### ISSUE THREAD

**Issue by Shrif88** [atom/one-dark-ui#254]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
When changing font size by entering double digit integer the Font Size field, it promptly and intently reads the first digit and takes a prompt action to change the font size. For example. when entering 14, the field will switch to 1 and does not wait long enough till the user enters the full value which is 14 and this will reset UI to value 8 because value 1 is not valid font size.

### Steps to Reproduce

1. Go to Settings > Themes > Select One Dark UI > Settings > Font Size
2. Enter 14

**Expected behavior:** UI font size should switch to 14 

**Actual behavior:** UI font size switches to 8

**Reproduces how often:** always

### Versions

Atom    : 1.25.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.25.0
python 2.7.12
git 2.7.4

### Additional Information
There is two workrounds
1. Write the value in any where like in a txt file and copy the value and past it in the font size field 
2. Write the value very quickly

**Comment by rsese** [comment]
Thanks for the report - this is addressed in 1.26 (which is currently in beta) by using a dropdown rather than a text input, see https://github.com/atom/one-dark-ui/pull/245.
