### ISSUE TITLE
<unknown> is deprecated.

### ISSUE THREAD

**Issue by ratheeshkm** [atom/one-dark-ui#258]
You have the core package "one-dark-ui" installed as a community package. See https://github.com/atom/dalek for how this causes problems and instructions on how to correct the situation.
```
<unknown> (<embedded>:13400:20)
Generator.next (null:null:null)
step (<embedded>:13387:279)
<unknown> (null:null:null)
process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by 50Wliu** [comment]
See https://github.com/atom/dalek#i-got-a-warning-what-do-i-do for how to fix this issue.
