### ISSUE TITLE
Increase text contrast

### ISSUE THREAD

**Issue by postcasio** [atom/one-dark-ui#26]
The original plan for these themes was configurable settings but since that's being pushed back, what do you think about increasing the contrast slightly? Personally I find the default colour for the tree-view/tab/status-bar text to be quite dark and hard to read.

I think changing the max lightness for `@ui-fg` to 70% is a subtle change but helps legibility a lot:

before:
![screen shot 2015-03-26 at 16 56 15](https://cloud.githubusercontent.com/assets/1759837/6851839/575d6264-d3d9-11e4-824f-30d2b27a1ee9.png)

after:
![screen shot 2015-03-26 at 16 55 54](https://cloud.githubusercontent.com/assets/1759837/6851846/5a0f9536-d3d9-11e4-9b40-fb9e612b2ba3.png)

This is using `one-dark-syntax`, btw.

**Comment by simurai** [comment]
Yeah, I find it depends a lot on the environment. If you're in a dark room, low contrast is easier on the eyes. But then during the day it's too weak and with sunlight kinda unusable.

We can increase the default a bit. Maybe too much contrast is still better than too low.

**Comment by mnquintana** [comment]
I'm sort of torn on this – I do remember thinking that One Dark seemed a little "murky" compared to Atom Dark when I first switched, but I've found that I'm able to work in Atom indefinitely now without my eyes hurting, which was definitely not the case with Atom Dark. 70% seems a little too bright to me – maybe something like 65% instead?

**Comment by simurai** [comment]
Ok.. changed it to `66%`? It's a rounded down `2/3`. Not that it means much, but sounds good. :smirk_cat:
