### ISSUE TITLE
Background colors are mismatched

### ISSUE THREAD

**Issue by brendanfalkowski** [atom/one-dark-ui#266]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The `One Dark UI` and `One Dark Syntax` apply background colors that are slightly off each other, which creates a weird "boxed" effect. Screenshot:

<img width="639" alt="screen shot 2018-06-26 at 2 27 56 pm" src="https://user-images.githubusercontent.com/214924/41940498-be9aafb4-794d-11e8-9d08-0fa2d78d2a77.png">

Note: I can barely see this on my Dell monitor, but I noticed it immediately when using a Mac laptop which has better color reproduction.

Here's the same screenshot manipulated to exaggerate the mismatched background colors:

![artboard](https://user-images.githubusercontent.com/214924/41940957-689f16de-794f-11e8-8da4-aae1e75dddeb.png)

The colors slightly off (original screenshot):

* `#282C34` — Editor background
* `#292D34` — Text "blocking"
* `#292D34` — Active tab background

### Steps to Reproduce

1. Use the `One Dark` syntax and UI themes.

**Expected behavior:** The editor background, active tab background, and text "blocking" should be the same color.

**Actual behavior:** The active tab background and text "blocking" should be the same color as the editor background.

**Reproduces how often:** 100%

### Versions

Atom    : 1.28.0
Electron: 2.0.3
Chrome  : 61.0.3163.100
Node    : 8.9.3

Mac 10.13.5

**Comment by brendanfalkowski** [comment]
@rsese — Thanks, that sounds plausible. Weirdly after re-docking to the Dell monitor this issue corrected itself. I tried swapping the color profile settings, but couldn't reproduce it.

**Comment by rsese** [comment]
Oh huh that is weird, but I'm glad things are looking ok for you now - if this color rendering issue does happen pop up for you again, go ahead and give that setting a try and let us know if it doesn't fix things for you.

**Comment by nelson6e65** [comment]
> Try updating Settings > Color Profile to Use sRGB color profile and let us know if that restores the color rendering you saw previously.

Thanks, @rsese This solves my issue.
