### ISSUE TITLE
Dropdown menus are cut off

### ISSUE THREAD

**Issue by Stanzilla** [atom/one-dark-ui#33]
![2015-04-07_09-44-41](https://cloud.githubusercontent.com/assets/75278/7018932/bebdc6da-dd0a-11e4-9fe8-51b9acb1bcee.png)
![2015-04-07_09-44-11](https://cloud.githubusercontent.com/assets/75278/7018933/c141cdc0-dd0a-11e4-84c3-eed550782c7d.png)

**Comment by izuzak** [comment]
I'm not seeing this, @Stanzilla. Which version of Atom are you using and which OS? Can you share more information? 

![screen shot 2015-04-07 at 09 59 54](https://cloud.githubusercontent.com/assets/38924/7019119/e27fa8a2-dd0c-11e4-872b-80aa01c77992.png)

**Comment by simurai** [comment]
Looks like Windows. I'll see if I can reproduce it.

**Comment by simurai** [comment]
I could reproduce it on Windows. Should be fixed if you rebuild master.

**Comment by izuzak** [comment]
:heart:  @simurai

**Comment by Stanzilla** [comment]
Sorry that I did not provide more information, it was Windows 8, yes :) Thanks for fixing!
