### ISSUE TITLE
Recent update broke git-tab-status tab coloring

### ISSUE THREAD

**Issue by mnquintana** [atom/one-dark-ui#35]
I haven't quite pinpointed which commit did it, but one of the recent updates (since Atom 0.189.0 was tagged) broke [git-tab-status](https://atom.io/packages/git-tab-status) - it now no longer colors the tabs based on their files' git status. It does still work with Atom Dark and Light and other themes though.

(Also applies to One Light UI)

**Comment by mnquintana** [comment]
Actually I think it was https://github.com/atom/one-dark-ui/commit/57198e273a136550209668f0eb57acf0dea76e5f

**Comment by simurai** [comment]
I see.. git-tab-status adds classes to the title. Will move the color to the parent element.
