### ISSUE TITLE
Find in selection button to big

### ISSUE THREAD

**Issue by philipgiuliani** [atom/one-dark-ui#36]
The find in selection button size is wrong with the current version. Only happens when the `option-selection` class is applied. Thanks :+1: 

**UPDATE**
I also just noticed that "no results" isn't centered ;)

![bildschirmfoto 2015-04-07 um 16 10 01](https://cloud.githubusercontent.com/assets/5446019/7024966/aaad981a-dd40-11e4-9d1d-74a5ff279ae1.png)

**Comment by simurai** [comment]
I can't reproduce it in Atom `0.190.0`. But I've seen it at some point. Are you building Atom locally? Or updating One dark manually?

One dark `0.6.0` depends on find-and-replace `0.160.0`.

**Comment by philipgiuliani** [comment]
After updating today i also havent seen it :) I had installed the package
manually to try the newest version (with the old atom version). Ill close
it as soon as im on the pc.

simurai <notifications@github.com> schrieb am Mi., 8. Apr. 2015 10:42:

**Comment by braver** [comment]
It can depend on the environment, because some fonts actually don't have a glyph for that. IIRC if it falls back to Times New Roman, sizing goes out of whack. Would be better if these were icons rather than text.

**Comment by simurai** [comment]
> Would be better if these were icons rather than text.

:+1: Yes, real icons will come: https://github.com/atom/find-and-replace/issues/370
