### ISSUE TITLE
Active tab color conflicts with timecop pane

### ISSUE THREAD

**Issue by grizzilus** [atom/one-dark-ui#38]
Not sure if this is a theme issue or a timecop issue, but the active tab color doesn't match the background for the timecop pane. It looks strange compared to regular editors where the active tab color matches the background color.
 
![screen shot 2015-04-07 at 10 38 55 pm](https://cloud.githubusercontent.com/assets/4955347/7039624/96df8206-dd79-11e4-9c6c-12339483f3d2.png)

This is atom 0.190.

**Comment by simurai** [comment]
:+1:  Will look like this:

![screen shot 2015-04-14 at 5 33 54 pm](https://cloud.githubusercontent.com/assets/378023/7133297/cf852d1a-e2cc-11e4-88fb-194ce52fddce.png)
