### ISSUE TITLE
Tab corners are a bit crummy with ligt syntax theme

### ISSUE THREAD

**Issue by braver** [atom/one-dark-ui#42]
With a light syntax theme you kinda lose the nice rounded corners.

![screen shot 2015-04-08 at 10 26 16](https://cloud.githubusercontent.com/assets/2543659/7042021/d414fc36-ddde-11e4-967f-6fd8f752a589.png)

**Comment by simurai** [comment]
![screen shot 2015-04-09 at 12 36 03 am](https://cloud.githubusercontent.com/assets/378023/7048873/72b5b472-de50-11e4-8a1d-6e70933101c6.png)

And just found another issue. The close button has a too weak hover state.
