### ISSUE TITLE
markdown-preview table text is too light

### ISSUE THREAD

**Issue by alexrussell** [atom/one-dark-ui#43]
The [markdown-preview less file](https://github.com/atom/markdown-preview/blob/master/styles/markdown-preview.less#L285-L293) has a white (or light in the case of zebra) override for tables. Before this package started messing with text and background colours that was fine as the default was black or some dark text colour. However, this package [overrides the default](https://github.com/atom/one-dark-ui/blob/master/styles/packages.less#L65-L66) text colour to be a light grey on top of a dark grey. That's fine for normal text, but with the table background override to white, the text is light grey on top of white.

![markdown bads](https://cloud.githubusercontent.com/assets/412784/7043617/f1acee26-dde2-11e4-97d7-e35613bd5a45.png)

I'm not sure if this is the place to post this issue or not - realistically this package breaks the original working code, but at the same time the responsibility may be in the hands of the background colour override. So there are two solutions:

- This package changes styles/packages.less to add a `table tr` rule that defines the background to be the default, or text colour to something darker.

- markdown-preiew changes styles/markdown-preview.less to specify a text colour with the background colour override. This is actually more correct in terms of best practices I guess - if you change a background, you should specify a foreground as you can't rely on whatever it was before, but I think the fact that this package overrides markdown-preview's own styles in the first place suggests that we're not necessarily following absolute best practices here.

**Comment by simurai** [comment]
I added some styling for tables. Gonna look like this:

![screen shot 2015-04-09 at 1 01 26 am](https://cloud.githubusercontent.com/assets/378023/7049398/17d891ce-de54-11e4-810f-3560f8f5a242.png)

@alexrussell Thanks for noticing.

**Comment by alexrussell** [comment]
:clap:
