### ISSUE TITLE
Modal overlay borders are a bit messed up

### ISSUE THREAD

**Issue by jakecleary** [atom/one-dark-ui#44]
Hey,

Firstly, thanks for the great theme!

The left inner border of the modal overlay seems to be missing. See the image below.

Thanks in advance :smile: 

![screenshot 2015-04-08 14 33 10](https://cloud.githubusercontent.com/assets/4572429/7046251/53d6da62-ddfc-11e4-838c-fbe81a2a3096.png)

**Comment by simurai** [comment]
Looks like this got fixed by "accident" when reducing the padding in #41. Will be in the next release.
