### ISSUE TITLE
Keep UI monochrome if Syntax BG has no saturation

### ISSUE THREAD

**Issue by simurai** [atom/one-dark-ui#45]
Came up in this discussion: https://discuss.atom.io/t/what-color-in-a-theme-is-causing-the-ui-to-get-pink-text/16016

**Comment by robneu** [comment]
+1 I also have pink text everywhere at the moment. :(

**Comment by simurai** [comment]
Will be in the next update.

**Comment by robneu** [comment]
Thank you!! :100:
