### ISSUE TITLE
Weird overlap when dragging tab to active tab position

### ISSUE THREAD

**Issue by mnquintana** [atom/one-dark-ui#50]
When dragging a tab to the left of the active tab, the two indicators overlap and look sort of strange. (Also applies to one-light-ui)

![screenshot_2015-04-13_08_21_00](https://cloud.githubusercontent.com/assets/823545/7115380/3b61e180-e1b6-11e4-9448-0a605ef5dfa9.png)

**Comment by sanicki** [comment]
I am seeing the blue vertical indicator double in width when they overlap. Is this what you're referring to? Do you have a suggestion for how this can be improved?

**Comment by mnquintana** [comment]
@sanicki Yup, it doubles in width, and the "move-to-here" indicator is slightly taller than the active tab indicator, which creates the sideways "step pyramid" shape in the screenshot (it's a lot easier to see if you look at it full-size).

I can think of a few possible solutions:
- Hide the active tab indicator when dragging a tab to that position
- Shorten the "move-to-here" indicator to match the height of the active tab indicator

**Comment by mnquintana** [comment]
I can't reproduce this anymore with the latest version.

**Comment by simurai** [comment]
Good to know.. wasn't intentionally fixed. :satisfied:
