### ISSUE TITLE
Could we try a longer max length on tab titles?

### ISSUE THREAD

**Issue by nathansobo** [atom/one-dark-ui#55]
Loving the increased padding overall, but I wonder if we could show more of the tab title before resorting to ellipses. Seems like it might be nice to let the tabs breathe a bit horizontally if we have the space.

![screenshot 2015-04-20 20 35 41](https://cloud.githubusercontent.com/assets/1789/7244822/6eaff0ac-e79e-11e4-9479-e18b65d994a8.png)

I've got miles of tab bar here but I can't read my file extensions.

**Comment by simurai** [comment]
There is a related discussion #49 and in the `sm-tabs` branch, the max width is already much larger, but we can close this if/once that gets merged.

**Comment by simurai** [comment]
Larger max-width will be in Atom `0.197.0`.

![screen shot 2015-05-03 at 12 04 49 am](https://cloud.githubusercontent.com/assets/378023/7441651/2fc9cd08-f12c-11e4-8dfc-c86825f8028f.png)

**Comment by nathansobo** [comment]
❤️
