### ISSUE TITLE
Consider publishing to npm

### ISSUE THREAD

**Issue by kriskowal** [atom/one-dark-ui#56]
I hope to use this outside the scope of Atom. npm would be a good fit.

**Comment by kriskowal** [comment]
…an ambition that is complicated because Less doesn’t do fancy dependency management, alas. Ran into trouble importing octicon-mixins.

**Comment by simurai** [comment]
Yeah, Atom themes are styled on top of Atom and can't really be used just by themselves. They're dependent on a certain markup and the core Atom styles.

**Comment by kriskowal** [comment]
The kind folks maintaining less for Node.js have pointed me in the direction of less-plugin-npm-import, which would get me most of the way to being able to import from packages. I might be able to build on this model to make a plugin for Less that would work both client side and server side, using Mr to locate dependencies. If I get that far, I might fork this, factor its dependencies into packages, and elide others. Not sure how far I will get. Safe to resolve this as “considered” for now.

**Comment by kriskowal** [comment]
Oh, for context https://github.com/less/less.js/issues/2572
