### ISSUE TITLE
Padding of tree-view project node is "wrong"...

### ISSUE THREAD

**Issue by thomasjo** [atom/one-dark-ui#61]
... in *Spacious* mode

![image](https://cloud.githubusercontent.com/assets/3622/7525538/8324fd7e-f50a-11e4-8440-a5190f7cbc72.png)

Changing the `padding-top` value from `0.75em` to `0.5em` seems to fix it, but not entirely sure that looks like what you intended. For reference, it looks fine in *Compact* mode.

**Comment by simurai** [comment]
Also adding your "1px off" screenshot for compact mode:

![pasted_image_at_2015_05_07_23_10](https://cloud.githubusercontent.com/assets/378023/7528778/a5cdba06-f568-11e4-8180-164af416dca0.png)
