### ISSUE TITLE
Auto Layout Mode doesn't respect chosen font-size

### ISSUE THREAD

**Issue by DaanDD** [atom/one-dark-ui#62]
I recently updated Atom and suddenly the text in the sidebar and settings screen became way too big because of the new Auto Layout Mode. I understand that there could be some extra spacing on big screens, but scaling the font-size makes the interface look a bit weird when the user has chosen a smaller font-size. This is what it looks like:

![screen shot 2015-05-08 at 14 54 43](https://cloud.githubusercontent.com/assets/1300724/7536903/62500fe6-f594-11e4-9729-d5896317e57e.png)

As you can see, the font-size in the sidebar and tabs is bigger while the font-size of the code itself doesn't change. I would prefer if only the spacing changed while the chosen font-size remained the same. A good example of this would be the Gmail interface, which also gives you the option to choose between a more spacious or compact layout.

**Comment by simurai** [comment]
An option would be to split the Layout Mode and "auto changing" of the font size into two different settings. Like:

Layout Mode [ Auto ]
- [x] Responsive Font Size

On the other hand, if you like to keep the Layout Mode to `Auto`, but the font-size should always stay the same, you can lock that by adding to your `styles.less` the following: 

```less
.theme-one-dark-ui {
  font-size: 12px;
}
```
