### ISSUE TITLE
Can't change layout mode in theme settings

### ISSUE THREAD

**Issue by antoine1fr** [atom/one-dark-ui#65]
The README and the changelog say I can switch between three layout modes (auto, compact and spacious) right in the theme settings panel. I haven't found such a switch.

**Comment by izuzak** [comment]
You should see it under Settings > Themes > One Dark UI:

![screen shot 2015-05-11 at 11 44 13](https://cloud.githubusercontent.com/assets/38924/7562243/1e5637a2-f7d3-11e4-998e-5c4d658c7727.png)

If you don't see it -- can you share the version of Atom you're using and a screenshot of the same screen?

**Comment by mnquintana** [comment]
This will get a bit easier to find with https://github.com/atom/settings-view/pull/481
