### ISSUE TITLE
Message 1px too high

### ISSUE THREAD

**Issue by braver** [atom/one-dark-ui#66]
It kinda sticks out one pixel.
![screen shot 2015-05-11 at 21 54 11](https://cloud.githubusercontent.com/assets/2543659/7573890/67e49e8a-f829-11e4-8de4-7150053c59c3.png)

**Comment by izuzak** [comment]
Yep, good eyes! Already reported here: https://github.com/atom/notifications/issues/57 so closing this to keep things organized.

**Comment by simurai** [comment]
Actually, this seems to be an issue with the One theme only. I'll move it back to here.

**Comment by braver** [comment]
I believe I applied a fix in `isotope`, but the problem is in the default styles.

**Comment by simurai** [comment]
Fixed in the notification package: https://github.com/atom/notifications/commit/e52aa2dfb4ffc5dde30278cf077694378db5770b
