### ISSUE TITLE
Monokai syntax makes the theme look washed out

### ISSUE THREAD

**Issue by kabalage** [atom/one-dark-ui#68]
I've been using one-dark-ui 0.5.0 for a while now, because the newer versions look washed out, too light with Monokai. The contrast and brightness is ok with one-dark-syntax tough.

0.8.1 (current version):
![one-dark-ui-monokai-toolight](https://cloud.githubusercontent.com/assets/7619177/7628992/59417c16-fa29-11e4-9df7-50db7a3da6b4.png)

0.5.0:
![one-dark-ui-monokai-olderversion](https://cloud.githubusercontent.com/assets/7619177/7628999/618a614e-fa29-11e4-9e10-ad87f6d835e4.png)

**Comment by simurai** [comment]
Currently the logic is like this: The UI around the editor is a bit darker than the background of the syntax theme. But if the background gets close to black, the UI inverts and gets brighter instead. `0.5.0` stays dark no matter.

So maybe the threshold could be lowered a bit.

**Comment by simurai** [comment]
In the next update, Monokai should look like this:

![screen shot 2015-05-27 at 12 22 28 am](https://cloud.githubusercontent.com/assets/378023/7830577/adc62a06-0489-11e5-8e47-c397c315ea4f.png)
