### ISSUE TITLE
Failed to activate the one-dark-ui theme

### ISSUE THREAD

**Issue by batjko** [atom/one-dark-ui#70]
1. Having a different theme activated (Isotope UI), attempt to switch to One Dark UI.
2. Observe Errors popping up, without changing the theme:

![image](https://cloud.githubusercontent.com/assets/7287076/7660157/65b84f08-fb3f-11e4-816a-81928ef0e684.png)

Note that this keeps coming up, even if I reload or completely restart the editor.
However, I can change to Atom Dark or Light without a problem.

**Atom Version**: 0.199.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [one-dark-ui](https://github.com/atom/one-dark-ui) package, v0.8.1

### Stack Trace

Failed to activate the one-dark-ui theme

```
At Recursive variable definition for @button-background-color in C:\Users\free\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\one-dark-ui\index.less:28:4

LessError: Recursive variable definition for @button-background-color
  at C:\Users\free\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\one-dark-ui\index.less:28:4
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "minimap",
      "enhanced-package-list",
      "themed-settings"
    ],
    "themes": [
      "one-dark-ui",
      "kuali-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
coffee-navigator, v0.0.16
file-icons, v1.5.5
git-log, v0.3.0
kuali-dark-syntax, v1.3.0
symbols-tree-view, v0.9.2

# Dev
No dev packages
```

**Comment by batjko** [comment]
I just noticed that I also get it for One Light UI, but I'm holding off opening an issue on that repo until I know more about this one.

![image](https://cloud.githubusercontent.com/assets/7287076/7660252/1ad647f0-fb40-11e4-8336-ecfffdf36987.png)

**Comment by simurai** [comment]
Seems like `kuali-dark-syntax` conflicts with One light/dark. Other syntax themes are fine.

**Comment by simurai** [comment]
Ok, I think the problem is that Kuali Dark has a variable called `@bg` https://github.com/murphyrandle/atom-kuali-dark-syntax/blob/master/styles/colors.less#L9 and then One dark/light also have the same `@bg` variable: https://github.com/atom/one-dark-ui/blob/master/styles/buttons.less#L38

Does Less have scoped variables to just a ruleset?

**Comment by batjko** [comment]
So the scopes of UI and syntax themes can pollute each other?

**Comment by simurai** [comment]
Yeah, if they import each others variables and use the same variable names there is a change they conflict. Usually it should just override each other, but maybe in this case it was problematic because the `@bg` variable was used inside a mixin that got called from different places.

**Comment by batjko** [comment]
Interesting.
Indeed if I switch the syntax theme to something else first, One UI works ok again.
