### ISSUE TITLE
Install panel's Themes / Packages toggle is a different height than the search input

### ISSUE THREAD

**Issue by mnquintana** [atom/one-dark-ui#71]
One Dark:

![image](https://cloud.githubusercontent.com/assets/823545/7683527/b88985de-fd4d-11e4-9a49-d9c7c76a8d53.png)

Atom Dark:
![image](https://cloud.githubusercontent.com/assets/823545/7683553/dffbcfaa-fd4d-11e4-8d33-4917b1653896.png)

Also applies to One Light.

**Comment by simurai** [comment]
@mnquintana Thanks for making an issue about it.. was bugging me too.
