### ISSUE TITLE
Disable tab marker when tree-view has focus

### ISSUE THREAD

**Issue by simurai** [atom/one-dark-ui#75]
Came up in https://github.com/atom/tree-view/issues/455#issuecomment-106511079

> @bronson Part of the confusion might be that the treeview's tab is focused differently.
> 
> Normally, when a tab receives the blue highlight, the old tab gives up its highlight.  When treeview is focused, however, the previous tab doesn't change its appearance at all.

![treeview focus](https://cloud.githubusercontent.com/assets/1776/7866477/aa76c996-0524-11e5-848b-244a99c6af15.gif)

**Comment by simurai** [comment]
Seems that `atom-pane` don't get focus, so `atom-pane.active:focus` has no effect. It probably got disabled for some reason.

An option might be to remove `active` when panes get blurred?

**Comment by marcofugaro** [comment]
yup, I miss the active tab highlight especially when focusing on the tree-view with `ctrl-0` (which I remapped to `alt-tab`).

I use that often so it's upsetting for me.

**Comment by simurai** [comment]
Closing..

The tree-view now shows a stronger selection color when focused.

![tree-view](https://user-images.githubusercontent.com/378023/44467330-91051980-a65d-11e8-9394-236c190b048c.gif)
