### ISSUE TITLE
Getting white tabs when using the base16-syntax theme

### ISSUE THREAD

**Issue by marshallbu** [atom/one-dark-ui#78]
![screen shot 2015-06-09 at 12 39 41 pm](https://cloud.githubusercontent.com/assets/607054/8067778/bdd4dec2-0ea4-11e5-97fc-acde135774ef.png)

I've tried debugging with dev tools, but can't pinpoint any style being applied so I'm assuming its defaulting to the core 'white' color I see mentioned in a previous issue.

**Comment by simurai** [comment]
Right. One dark tries to import the `syntax-variables.less` file and then use the `@syntax-background-color`. But in the case of the base16-syntax theme, it seems not be available and then it defaults to white.

The base16-syntax theme is special since it generates and injects the CSS itself, I think? Not sure if it's possible to also generate a `syntax-variables.less` file with the right variables. Might be worth to ask.

**Comment by marshallbu** [comment]
Yeah, it looks like it has a a `syntax-variables-{dark/light}.less` file, which I assume it switches back and forth for it's dark vs light setting.  I'll dig around and see if there's a way, thanks!

**Comment by lunelson** [comment]
I'm getting this too, using this theme https://github.com/blakehall/tomorrow-night-eighties

**Comment by simurai** [comment]
@lunelson The `syntax-variables.less` is missing in the tomorrow-night-eighties theme as well. Which then falls back to `white` in [Core](https://github.com/atom/atom/blob/master/static/variables/ui-variables.less#L25).

You could try to add an issue on the tomorrow-night-eighties repo and see if it gets added.

**Comment by lunelson** [comment]
@simurai thanks I'll look in to that. Maybe I'll just start a new theme from boilerplate and port the values from that one, as they work nicely otherwise with the Atom One UI

**Comment by simurai** [comment]
I'll close this since this theme can't do much about it and it would need to be changed in those syntax themes.

**Comment by Alchiadus** [comment]
I have updated [base16-syntax](https://github.com/Alchiadus/base16-syntax). It now generates a `styles/syntax-variables.less` file so other packages can properly access it. @lunelson base16-syntax includes the Eighties scheme, which might be what you are looking for.

**Comment by simurai** [comment]
@Alchiadus Awesome!

**Comment by lunelson** [comment]
Thanks @Alchiadus I'll check it out :+1:

**Comment by marshallbu** [comment]
Works like a charm, thanks!!
