### ISSUE TITLE
Bad scrollbar position in Command Palette on OSX 10.9

### ISSUE THREAD

**Issue by matiasgarciaisaia** [atom/one-dark-ui#79]
![scrollbar-palette](https://cloud.githubusercontent.com/assets/5470539/8187472/3a64b1a2-1426-11e5-891a-fc78e32e7c4b.gif)

I found it easier to reproduce by opening the palette with no editors opened - but it happened with an editor opened after changing the window size.

It happens too on the one-light-ui theme, but not on Atom Dark UI.

**Comment by simurai** [comment]
> @matiasgarciaisaia I found it easier to reproduce by opening the palette with no editors opened

With no editors open, can you reproduce it every time or just sometimes?

I can't reproduce it at all, but I'm on OS X 10.10. Not sure if that matters.

Also, what happens if you change "Show scroll bars" to "Always" in the General OS X settings. Does it happen then too?

![screen shot 2015-06-19 at 10 54 16 am](https://cloud.githubusercontent.com/assets/378023/8245998/05ad978c-1672-11e5-81a1-0338963f1c6a.png)

**Comment by matiasgarciaisaia** [comment]
@simurai: it doesn't seem to happen _everytime_ now - it's even not happening with no editors opened, but started to happen when editors _are_ opened.

I could easily reproduce this in the last 5 minutes I've been trying:

![scrollbar-recap](https://cloud.githubusercontent.com/assets/5470539/8246699/61342566-1619-11e5-9a8a-55f76cc1df99.gif)

But it's exactly the opposite of what happened the day I reported this - then it was easy to reproduce it with no editors opened, and with editors opened it worked OK most of the times.

@lee-dohm was able to reproduce it on his own setup, too - I don't know if he recalls.


I have upgraded from 0.209.0 to 0.210.0 today, so I don't know if that changes anything.

But I do remember that the day I opened the issue it almost always (or maybe always, I'm not _that_ sure) showed the bars wrong without open editors, and I remember at least one time (but it was not "common") that happened _with_ opened editors.


I've just tried opening the editor with a local project (`atom .` while being in a project) and the error haven't happened - with nor without opened editors.


Changing that setting to Always showing the scrollbars I wasn't able to reproduce the bug, neither. My current setting is "Automatically based on mouse or trackpad". Choosing "When scrolling" did reproduce the bug.


I hope this helps :/

**Comment by simurai** [comment]
Ohh.. I can reproduce it now. As soon as I move Atom from a non-retina to a retina screen, then the scrollbars are always half way.

Fixed it on the [sm-modal-fix](https://github.com/atom/one-dark-ui/tree/sm-modal-fix) branch. Gonna test it for a bit to see if there are no other side effects.

**Comment by simurai** [comment]
Added a fix.. should be in the next release.

@matiasgarciaisaia Feel free to comment again if the issue stays.

**Comment by matiasgarciaisaia** [comment]
Just tried, and couldn't reproduce - seems effectively be fixed.

Thanks :)
