### ISSUE TITLE
Changelogs don't have a tab title anymore

### ISSUE THREAD

**Issue by 50Wliu** [atom/one-dark-ui#85]
_From @Stanzilla on July 20, 2015 15:39_

On 1.0.2

![changelog md_preview_-_cusersbenjamindocuments_2015-07-20_17-38-47](https://cloud.githubusercontent.com/assets/75278/8779950/53047972-2f06-11e5-9b77-446d22c30737.png)

When you tab away from it, the text shows up. So it might just be a text color problem?

_Copied from original issue: atom/settings-view#596_

**Comment by 50Wliu** [comment]
Does this happen with all UI themes or just one-dark?

**Comment by 50Wliu** [comment]
_From @Stanzilla on July 20, 2015 21:39_

Ah damn, should have tested that before. Yeah it's only happening in One Dark. Can you move the issue, please?

**Comment by mnquintana** [comment]
I can reproduce this with Atom 1.0.3-0fe4183

**Comment by benogle** [comment]
Also markdown preview tabs dont have it either

![screen shot 2015-07-20 at 3 13 45 pm](https://cloud.githubusercontent.com/assets/69169/8788812/ffd33400-2ef1-11e5-92b8-2b691ad8e6b4.png)

wtf

**Comment by mnquintana** [comment]
I'm wondering if it might have something to do with https://github.com/atom/one-dark-ui/commit/223743885172cf8ae697f309023ff2c2dfa10a57

**Comment by benogle** [comment]
Good call, there definitely is data in there

**Comment by benogle** [comment]
![screen shot 2015-07-20 at 3 18 19 pm](https://cloud.githubusercontent.com/assets/69169/8788887/a015750e-2ef2-11e5-94e2-775476a5763f.png)
