### ISSUE TITLE
Missing filetype icons on theme

### ISSUE THREAD

**Issue by denisinla** [atom/one-dark-ui#86]
I recently updated atom and noticed that the filetype icons for one-dark-ui are not rendering instead I have placeholders. Any ideas?

**Comment by simurai** [comment]
@denisinla With "placeholders", do you mean like this: 
![screen shot 2015-07-23 at 10 05 05 am](https://cloud.githubusercontent.com/assets/378023/8840895/56678b68-3122-11e5-812a-a6393ab22fab.png)

If so, that's the default icons. There are packages that add filetype icons like https://atom.io/packages/file-icons or https://atom.io/packages/seti-icons. Maybe you had it installed and they somehow got disabled?

**Comment by denisinla** [comment]
@simurai Awesome that was it, for some strange reason when I updated Atom file-icons were gone.

**Comment by thomasjo** [comment]
`file-icons` is not a bundled package, and never has been. Thanks to @simurai for helping you resolve your problem.
