### ISSUE TITLE
One dark theme for xCode

### ISSUE THREAD

**Issue by JeanLebrument** [atom/one-dark-ui#90]
Hi,

I didn't find anything on Google relative to a version of the One Dark theme for xCode. 

Is there such a theme available or even a close one?

Thanks !

**Comment by jerone** [comment]
You can use https://discuss.atom.io/ to start Atom related discussions or questions.

**Comment by thomasjo** [comment]
@JeanLebrument Do as @jerone suggests, as this theme is specifically created for Atom. You or someone else will have to create a port of this theme for Xcode.

**Comment by istx25** [comment]
Was this every made? :panda_face:

**Comment by istx25** [comment]
Was this ever made? :panda_face:

**Comment by tomislav** [comment]
Try https://libraries.io/alcatraz/One%20Dark%20for%20Xcode

**Comment by m1r4ge** [comment]
Check this one: [xcode-one-dark](https://github.com/bojan/xcode-one-dark)

**Comment by onmyway133** [comment]
Also check out DarkSide theme https://github.com/onmyway133/DarkSide
