### ISSUE TITLE
Serif font being used tab hover

### ISSUE THREAD

**Issue by johnmuhl** [atom/one-dark-ui#97]
![screen shot 2015-09-16 at 15 42 29](https://cloud.githubusercontent.com/assets/7944/9917958/f4ffe472-5c89-11e5-803e-30aa3c0360f2.png)

```
atom -v
1.0.12-dev-87b412c
```

**Comment by simurai** [comment]
This should be fixed if https://github.com/atom/atom/pull/8817 gets merged.

**Comment by mnquintana** [comment]
This should be fixed on `master` already since those changes were reverted. :sparkles:
