### ISSUE TITLE
Some more hardcoded fonts

### ISSUE THREAD

**Issue by p-e-w** [atom/one-dark-ui#99]
https://github.com/atom/one-dark-ui/pull/98 is awesome, but there are still hardcoded fonts left [here](https://github.com/atom/one-dark-ui/blob/e36722ff19d77aff0089b2d4987f9c2bf5ba5b63/styles/key-binding.less#L6) and [here](https://github.com/atom/one-dark-ui/blob/e36722ff19d77aff0089b2d4987f9c2bf5ba5b63/styles/tooltips.less#L21). These should use the system font as well.

**Comment by simurai** [comment]
I've been wondering if having the keybindings in `Helvetica Neue` was intentional?

Do all (most) fonts support characters like `⌥⌘` :

![screen shot 2015-09-17 at 9 40 57 pm](https://cloud.githubusercontent.com/assets/378023/9933324/32bf544a-5d85-11e5-8ff1-ddc3b557ffa3.png)

**Comment by braver** [comment]
@simurai If you would inspect that tooltip (or the keybinding examples in the style guide), you would see that it isn't rendered in Helvetica Neue at all. Apparently it doesn't contain the glyphs for those characters and Chrome falls back (at least on my Mac) to a combination of Lucida Grande and Arial. If you change the font-family to `system` it doesn't change anything, so my guess is SF doesn't have them either. In any case, you don't need to worry about special characters, Chrome will take care of that for you.

**Comment by simurai** [comment]
@braver Thanks for looking into it.

Ok, let's remove it. I guess `Helvetica Neue` just got added to override Bootstrap's `<kbd>` styling in select lists, but I'll change it to just `inherit` the font family.
